# Generated by Django 5.2.12 on 2026-03-18 18:55

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the customer (2-100 characters)",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="Customer Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional email for confirmation and follow-up",
                        max_length=254,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="US phone number (primary contact method)",
                        max_length=128,
                        region="US",
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Service location street address",
                        max_length=255,
                        verbose_name="Street Address",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="City name",
                        max_length=100,
                        verbose_name="City",
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True,
                        help_text="US ZIP code (5 or 9 digit format)",
                        max_length=10,
                        verbose_name="ZIP Code",
                    ),
                ),
                (
                    "appliance_type",
                    models.CharField(
                        choices=[
                            ("refrigerator", "Refrigerator"),
                            ("washer", "Washing Machine"),
                            ("dryer", "Dryer"),
                            ("dishwasher", "Dishwasher"),
                            ("oven", "Oven/Range"),
                            ("microwave", "Microwave"),
                            ("freezer", "Freezer"),
                            ("garbage_disposal", "Garbage Disposal"),
                            ("ice_maker", "Ice Maker"),
                            ("wine_cooler", "Wine Cooler"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type of appliance needing repair",
                        max_length=50,
                        verbose_name="Appliance Type",
                    ),
                ),
                (
                    "appliance_brand",
                    models.CharField(
                        blank=True,
                        help_text="Brand/manufacturer (e.g., Samsung, LG, Whirlpool)",
                        max_length=100,
                        verbose_name="Appliance Brand",
                    ),
                ),
                (
                    "appliance_model",
                    models.CharField(
                        blank=True,
                        help_text="Appliance model number (if available)",
                        max_length=100,
                        verbose_name="Model Number",
                    ),
                ),
                (
                    "problem_description",
                    models.TextField(
                        help_text="Detailed description of the issue (minimum 10 characters)",
                        validators=[django.core.validators.MinLengthValidator(10)],
                        verbose_name="Problem Description",
                    ),
                ),
                (
                    "preferred_date",
                    models.DateField(
                        blank=True,
                        help_text="Customer's preferred service date",
                        null=True,
                        verbose_name="Preferred Date",
                    ),
                ),
                (
                    "preferred_time",
                    models.CharField(
                        choices=[
                            ("morning", "Morning (8AM - 12PM)"),
                            ("afternoon", "Afternoon (12PM - 5PM)"),
                            ("evening", "Evening (5PM - 8PM)"),
                            ("anytime", "Anytime"),
                        ],
                        default="anytime",
                        help_text="Preferred time slot for service",
                        max_length=20,
                        verbose_name="Preferred Time",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_response", "No Response"),
                        ],
                        db_index=True,
                        default="new",
                        help_text="Current status of this booking request",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        help_text="Priority level for scheduling",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("google", "Google Search"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("yelp", "Yelp"),
                            ("referral", "Friend/Family Referral"),
                            ("repeat", "Repeat Customer"),
                            ("flyer", "Flyer/Print Ad"),
                            ("other", "Other"),
                        ],
                        help_text="How the customer heard about us",
                        max_length=30,
                        verbose_name="Lead Source",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Captured for spam prevention",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Browser/device information",
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Staff notes (not visible to customer)",
                        verbose_name="Internal Notes",
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(
                        blank=True,
                        help_text="Staff member or technician assigned to this booking",
                        max_length=100,
                        verbose_name="Assigned To",
                    ),
                ),
                (
                    "scheduled_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Confirmed appointment date and time",
                        null=True,
                        verbose_name="Scheduled Date/Time",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the service was completed",
                        null=True,
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this booking was submitted",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last modification timestamp",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific service requested (if known)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="services.service",
                        verbose_name="Requested Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_assign_booking", "Can assign bookings to technicians"),
                    ("can_export_bookings", "Can export booking data"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BookingNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        help_text="Staff member who added this note",
                        max_length=100,
                        verbose_name="Author",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Content of the note", verbose_name="Note Content"
                    ),
                ),
                (
                    "is_customer_visible",
                    models.BooleanField(
                        default=False,
                        help_text="If true, customer can see this note in their booking history",
                        verbose_name="Customer Visible",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        help_text="The booking this note belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_notes",
                        to="bookings.booking",
                        verbose_name="Booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Note",
                "verbose_name_plural": "Booking Notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "created_at"], name="bookings_bo_status_72dd85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["priority", "status"], name="bookings_bo_priorit_c4c322_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["phone"], name="bookings_bo_phone_fe5671_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["scheduled_datetime"], name="bookings_bo_schedul_8a0f72_idx"
            ),
        ),
    ]
