# Generated by Django 5.2.12 on 2026-03-18 18:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Display name for this service category (e.g., "Refrigerator Repair")',
                        max_length=100,
                        unique=True,
                        verbose_name="Category Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the name (auto-generated if blank)",
                        max_length=100,
                        unique=True,
                        verbose_name="URL Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of services in this category",
                        verbose_name="Description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text='CSS icon class (e.g., "fa-snowflake" for refrigerator)',
                        max_length=50,
                        verbose_name="Icon Class",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Representative image for this category (recommended: 400x300px)",
                        null=True,
                        upload_to="services/categories/",
                        verbose_name="Category Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive categories will not be displayed on the website",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which this category appears (lower numbers first)",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this category was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this category was last modified",
                        verbose_name="Updated At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Category",
                "verbose_name_plural": "Service Categories",
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"],
                        name="services_se_is_acti_fb7379_idx",
                    ),
                    models.Index(fields=["slug"], name="services_se_slug_89aee3_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Display name for this service (e.g., "Compressor Replacement")',
                        max_length=200,
                        verbose_name="Service Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the name",
                        max_length=200,
                        verbose_name="URL Slug",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Brief description for service listings (max 200 characters)",
                        max_length=200,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "full_description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description including what the service covers",
                        verbose_name="Full Description",
                    ),
                ),
                (
                    "price_from",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Starting or minimum price for this service (in USD)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Price From",
                    ),
                ),
                (
                    "price_to",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text='Maximum price (only used if price_type is "range")',
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Price To",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Price"),
                            ("starting_from", "Starting From"),
                            ("range", "Price Range"),
                            ("call", "Call for Quote"),
                        ],
                        default="starting_from",
                        help_text="How the price should be displayed on the website",
                        max_length=20,
                        verbose_name="Price Display Type",
                    ),
                ),
                (
                    "estimated_duration_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Estimated time to complete service (15-480 minutes)",
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(480),
                        ],
                        verbose_name="Estimated Duration (minutes)",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured services are highlighted on the homepage",
                        verbose_name="Is Featured",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive services will not be displayed on the website",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order within the category (lower numbers first)",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="The category this service belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="services.servicecategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["category", "display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_featured"],
                        name="services_se_is_acti_bfbbaa_idx",
                    ),
                    models.Index(
                        fields=["category", "is_active"],
                        name="services_se_categor_b50c86_idx",
                    ),
                ],
                "unique_together": {("category", "slug")},
            },
        ),
    ]
